name: Monthly Update Wrangler
on:
  schedule:
    - cron: '26 2 16 * *'
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  update:
    runs-on: ubuntu-latest
    name: Update Wrangler
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and Update Wrangler
        run: npm install --save-dev wrangler@latest

      - name: Auto Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: monthly update wrangler to latest"
          file_pattern: 'package.json package-lock.json'
